# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  - name: Visits
    url: '#visits'
    weight: 2
  - name: Experience
    url: '#experience'
    weight: 3
  - name: Metrics
    url: '#metrics'
    weight: 4
  - name: Publications
    url: '#publications'
    weight: 5
  - name: Talks
    url: '#talks'
    weight: 6
  - name: Academic Activity
    url: '#academic_activity'
    weight: 7
  - name: Teaching
    url: '#teaching'
    weight: 8
  - name: Honors
    url: '#honors'
    weight: 9
  - name: Contact
    url: '#contact'
    weight: 10
  - name: CV
    url: media/Curriculum_EN.pdf
    weight: 11
