# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: ocean
day_night: true
font: 'minimal'
font_size: L

# SEO

site_type: Person
local_business_type: ''
org_name: 'University of Udine'
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: michael.soprano@uniud.it
#phone: 888 888 88 88
address:
  street: "Department of Mathematics, Computer Science and Physics, Via delle Scienze 206"
  city: Udine (Italy)
  region:
  postcode: '33010'
  country: Italy
  country_code: IT
coordinates:
  latitude: '46.08008535022743'
  longitude: '13.211890024964413'
directions:
  Rizzi Building, 2° Floor, South Node, Lab SMDC (LC2-04-DE)
office_hours: ''
appointment_url: ''

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '15:04'
address_format: en-us

# Site features

highlight: true
#highlight_languages:
#  - r
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: chicago-b
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: 'mapbox'
  api_key: 'pk.eyJ1IjoibWljY2lnaGVsIiwiYSI6ImNrbWFzcjV3ZDF2MDIybnAxeTJ0MXo4MWEifQ.9e440PAeUo_ExG9Q7FEPbg'
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: hugo-version
  local_backend: false
icon:
  pack:
    ai: true
