appearance:
  theme: system
  theme_toggle: true
  avatar_shape: circle

search:
  enabled: true

header:
  sticky: true

locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'
  address_format: en-us

identity:
  name: Michael Soprano
  organization: University of Udine
  role: Researcher
  author_slug: michael-soprano
  tagline: Researcher in Human Computation and Information Retrieval
  description: Personal academic website of Michael Soprano, researcher at the University of Udine.
  social:
    twitter: Miccighel_

repository:
  enabled: false
